### Find All Content
GET http://localhost:8080/api/content

### Find Content by ID
GET http://localhost:8080/api/content/0

### Post Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 1,
  "title": "Another book",
  "authorName": "Another Author's name",
  "inventoryCount": 3,
  "lastEditDate": "2014-03-22"
}

### Updated existing Content
PUT http://localhost:8080/api/content/0
Content-Type: application/json

{
  "id": 0,
  "title": "Changed book title",
  "authorName": "Changed Author's name",
  "inventoryCount": 2,
  "lastEditDate": "2024-2-1"
}

### Delete existing Content
DELETE http://localhost:8080/api/content/0
